apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-deployment
  labels:
    app: health 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health 
  template:
    metadata:
      labels:
        app: health 
    spec:
      containers:
      - name: health 
        image: registry.gitlab.com/katsumeshi/health:v0.1.0
        ports:
          - containerPort: 3000
        command: ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]